# Generated by Django 3.2.16 on 2024-07-19 16:20

from django.db import migrations

def set_default_category(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    Product = apps.get_model('store', 'Product')
    default_category, created = Category.objects.get_or_create(name='Default Category')
    Product.objects.filter(category__isnull=True).update(category=default_category)
class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
    ]
